execute pathogen#infect()

set nocompatible
filetype off
set encoding=utf-8
set autoread
set listchars=trail:·
set list

set runtimepath^=~/.vim/bundle/neobundle.vim/

call neobundle#begin(expand('~/.vim/bundle/'))

NeoBundleFetch 'Shougo/neobundle.vim'

NeoBundle 'tpope/vim-fugitive.git'
NeoBundle 'kien/ctrlp.vim'
NeoBundle 'L9'
NeoBundle 'tpope/vim-rails'
NeoBundle 'tpope/vim-rake'
NeoBundle 'tpope/vim-bundler'
NeoBundle 'scrooloose/nerdtree'
NeoBundle 'tpope/vim-projectionist'
NeoBundle 'scrooloose/nerdcommenter'
NeoBundle 'matze/vim-move'
NeoBundle 'mileszs/ack.vim'
NeoBundle 'MarcWeber/vim-addon-mw-utils'
NeoBundle 'tomtom/tlib_vim'
NeoBundle 'garbas/vim-snipmate'
NeoBundle 'honza/vim-snippets'
NeoBundle 'terryma/vim-multiple-cursors'
NeoBundle 'vim-airline/vim-airline'
NeoBundle 'milkypostman/vim-togglelist'
NeoBundle 'Valloric/YouCompleteMe'
NeoBundle 'vim-airline/vim-airline-themes'
NeoBundle 'leafgarland/typescript-vim'
NeoBundle 'Shougo/vimproc.vim', {
\ 'build' : {
\     'windows' : 'tools\\update-dll-mingw',
\     'cygwin' : 'make -f make_cygwin.mak',
\     'mac' : 'make',
\     'linux' : 'make',
\     'unix' : 'gmake',
\    },
\ }

NeoBundle 'Quramy/tsuquyomi'

call neobundle#end()

syntax enable
set showcmd
filetype plugin indent on

NeoBundleCheck

set nowrap
set tabstop=2 shiftwidth=2
set expandtab
set backspace=indent,eol,start

set hlsearch
set incsearch
set ignorecase
set smartcase
set nu
set laststatus=2

set sw=2
set ts=2
set et
set iskeyword+=!,?,=

set guifont=Hack:h12
colorscheme atom-dark-256

set nobackup
set nowritebackup
set noswapfile

set wrap
set linebreak
set relativenumber

set clipboard=unnamed

" note trailing space at end of next line
" set showbreak=>\ \ \
set listchars=tab:\ \

"Autorefresh files
set autoread

" Remove trailing whitespace
autocmd FileType c,cpp,java,php,ruby,python,rb,coffee,js,html,css,scss,erb,haml,ts,styl,jade autocmd BufWritePre <buffer> :%s/\s\+$//e

" Misc mappings
:nmap <c-s> :w<CR>
:imap <c-s> <Esc>:w<CR>a

" Tsuquyomi
autocmd FileType typescript nmap <buffer> <Leader>e <Plug>(TsuquyomiRenameSymbol)
autocmd FileType typescript nmap <buffer> <Leader>E <Plug>(TsuquyomiRenameSymbolC)

" NERD Mappings
map <C-n> :NERDTreeToggle<CR>
nmap <leader>n :NERDTreeFind<CR>

" Tabs Mapping
map <C-t> :tabnew<CR>

" Don't be stupid!
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>

" Default mapping
let g:multi_cursor_next_key='<C-m>'
let g:multi_cursor_prev_key='<C-p>'
let g:multi_cursor_skip_key='<C-x>'
let g:multi_cursor_quit_key='<Esc>'

" Syntanstic
let g:syntastic_javascript_checkers = ['jshint']
let g:tsuquyomi_disable_quickfix = 1
let g:syntastic_typescript_checkers = ['tsuquyomi'] " You shouldn't use 'tsc' checker.

" Airline settings
let g:airline_theme = 'powerlinesh'
let g:airline_powerline_fonts = 1
let g:Powerline_symbols = 'fancy'

" Identline settings
let g:indentLine_enabled = 0

" Move lines
let g:move_key_modifier = 'C'
