# ZSH Config
export ZSH=~/.oh-my-zsh

plugins=(git rails google bundlerx command-not-found npm nyan history sudo wd web-search bundler tmuxinator tmux zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"

# Aliases
alias zshconfig="vim ~/.zshrc"
alias reload!="source ~/.zshrc"

# Functions
function git-clean {
  git fetch -u
  git branch --merged | grep -v '*' | grep -v master | grep -v development | ifne xargs -n 1 git branch -d
}

# NVM
export NVM_DIR="/home/aguz/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

# Load local configurations
if [[ -a ~/.localrc ]]; then
  source ~/.localrc
fi

# Set default editor
export EDITOR='nvim' #, of course

# Tmux
export DISABLE_AUTO_TITLE='true'

# Tmuxinator aliasses
alias tms='tmuxinator start'
alias tme='tmuxinator edit'
alias tmn='tmuxinator new'

# Neovim
alias vim=nvim

# Custom PATH
export PATH="$PATH:$HOME/.rvm/bin:$HOME/Android/Sdk/platform-tools:$HOME/Android/sdk/tools"
#export ANDROID_HOME=/Users/aguz/Library/Android/sdk
#export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

alias j='echo "Thanks! I needed that!"'

###-tns-completion-start-###
if [ -f /home/aguz/.tnsrc ]; then
    source /home/aguz/.tnsrc
fi
###-tns-completion-end-###


[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
