export ZSH=~/.oh-my-zsh

plugins=(
  git
  npm
)

source $ZSH/oh-my-zsh.sh

autoload -U promptinit; promptinit
prompt pure

# Aliases
alias zshconfig="vim ~/.zshrc"
alias reload!="source ~/.zshrc"
alias tms='tmuxinator start'
alias tme='tmuxinator edit'
alias tmn='tmuxinator new'
alias vim=nvim

# NVM
export NVM_DIR="/Users/aguz/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

# Load local configurations
if [[ -a ~/.localrc ]]; then
  source ~/.localrc
fi

# Set default editor
export EDITOR='nvim' #, of course

# Tmux
export DISABLE_AUTO_TITLE='true'
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
